"""events_hub_expansion

Revision ID: 28fbdf2816df
Revises: b6326fcb7067
Create Date: 2026-04-03 15:16:47.913619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28fbdf2816df'
down_revision: Union[str, Sequence[str], None] = 'b6326fcb7067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('h3_r7', sa.String(length=15), nullable=True),
    sa.Column('h3_r8', sa.String(length=15), nullable=True),
    sa.Column('h3_r9', sa.String(length=15), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', 'region', name='uq_venue_fp_region')
    )
    op.create_index(op.f('ix_venues_fingerprint'), 'venues', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_venues_h3_r7'), 'venues', ['h3_r7'], unique=False)
    op.create_index(op.f('ix_venues_h3_r8'), 'venues', ['h3_r8'], unique=False)
    op.create_index(op.f('ix_venues_h3_r9'), 'venues', ['h3_r9'], unique=False)
    op.create_index('ix_venues_h3r7_region', 'venues', ['h3_r7', 'region'], unique=False)
    op.create_index(op.f('ix_venues_region'), 'venues', ['region'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('raw_venue_name', sa.String(), nullable=True),
    sa.Column('raw_address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('h3_r7', sa.String(length=15), nullable=True),
    sa.Column('h3_r8', sa.String(length=15), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('ticket_url', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audience_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('social_density', sa.String(), nullable=True),
    sa.Column('friend_making_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_event_source_external')
    )
    op.create_index('ix_events_active_region', 'events', ['is_active', 'region'], unique=False)
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index('ix_events_category_active_region', 'events', ['category', 'is_active', 'region'], unique=False)
    op.create_index(op.f('ix_events_expires_at'), 'events', ['expires_at'], unique=False)
    op.create_index(op.f('ix_events_h3_r7'), 'events', ['h3_r7'], unique=False)
    op.create_index(op.f('ix_events_h3_r8'), 'events', ['h3_r8'], unique=False)
    op.create_index('ix_events_h3r7_active', 'events', ['h3_r7', 'is_active'], unique=False)
    op.create_index('ix_events_h3r8_active', 'events', ['h3_r8', 'is_active'], unique=False)
    op.create_index(op.f('ix_events_is_active'), 'events', ['is_active'], unique=False)
    op.create_index(op.f('ix_events_region'), 'events', ['region'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index('ix_events_start_active', 'events', ['start_time', 'is_active'], unique=False)
    op.create_index('ix_events_start_region_active', 'events', ['start_time', 'region', 'is_active'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.create_table('event_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_interactions_created_at'), 'event_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_interactions_event_id'), 'event_interactions', ['event_id'], unique=False)

    # ── New indexes on existing tables (plan items only) ──────────────
    op.create_index('ix_signals_observed_at', 'signals', ['observed_at'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_observed_at', table_name='signals')
    op.drop_index(op.f('ix_event_interactions_event_id'), table_name='event_interactions')
    op.drop_index(op.f('ix_event_interactions_created_at'), table_name='event_interactions')
    op.drop_table('event_interactions')
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index('ix_events_start_region_active', table_name='events')
    op.drop_index('ix_events_start_active', table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_region'), table_name='events')
    op.drop_index(op.f('ix_events_is_active'), table_name='events')
    op.drop_index('ix_events_h3r8_active', table_name='events')
    op.drop_index('ix_events_h3r7_active', table_name='events')
    op.drop_index(op.f('ix_events_h3_r8'), table_name='events')
    op.drop_index(op.f('ix_events_h3_r7'), table_name='events')
    op.drop_index(op.f('ix_events_expires_at'), table_name='events')
    op.drop_index('ix_events_category_active_region', table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_index('ix_events_active_region', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_venues_region'), table_name='venues')
    op.drop_index('ix_venues_h3r7_region', table_name='venues')
    op.drop_index(op.f('ix_venues_h3_r9'), table_name='venues')
    op.drop_index(op.f('ix_venues_h3_r8'), table_name='venues')
    op.drop_index(op.f('ix_venues_h3_r7'), table_name='venues')
    op.drop_index(op.f('ix_venues_fingerprint'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
