"""initial_schema

Revision ID: b6326fcb7067
Revises: 
Create Date: 2026-04-03 14:43:39.252841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6326fcb7067'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('h3_r7', sa.String(length=15), nullable=True),
    sa.Column('h3_r8', sa.String(length=15), nullable=True),
    sa.Column('h3_r9', sa.String(length=15), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', 'region', name='uq_venue_fp_region')
    )
    op.create_index(op.f('ix_venues_fingerprint'), 'venues', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_venues_h3_r7'), 'venues', ['h3_r7'], unique=False)
    op.create_index(op.f('ix_venues_h3_r8'), 'venues', ['h3_r8'], unique=False)
    op.create_index(op.f('ix_venues_h3_r9'), 'venues', ['h3_r9'], unique=False)
    op.create_index(op.f('ix_venues_region'), 'venues', ['region'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('raw_venue_name', sa.String(), nullable=True),
    sa.Column('raw_address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('h3_r7', sa.String(length=15), nullable=True),
    sa.Column('h3_r8', sa.String(length=15), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('ticket_url', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_event_source_external')
    )
    op.create_index('ix_events_active_region', 'events', ['is_active', 'region'], unique=False)
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index('ix_events_category_active_region', 'events', ['category', 'is_active', 'region'], unique=False)
    op.create_index(op.f('ix_events_expires_at'), 'events', ['expires_at'], unique=False)
    op.create_index(op.f('ix_events_h3_r7'), 'events', ['h3_r7'], unique=False)
    op.create_index(op.f('ix_events_h3_r8'), 'events', ['h3_r8'], unique=False)
    op.create_index('ix_events_h3r7_active', 'events', ['h3_r7', 'is_active'], unique=False)
    op.create_index('ix_events_h3r8_active', 'events', ['h3_r8', 'is_active'], unique=False)
    op.create_index(op.f('ix_events_is_active'), 'events', ['is_active'], unique=False)
    op.create_index(op.f('ix_events_region'), 'events', ['region'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index('ix_events_start_active', 'events', ['start_time', 'is_active'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.create_index(op.f('ix_api_request_log_requested_at'), 'api_request_log', ['requested_at'], unique=False)
    op.create_index(op.f('ix_api_request_log_source_key'), 'api_request_log', ['source_key'], unique=False)
    op.create_index(op.f('ix_api_sources_source_key'), 'api_sources', ['source_key'], unique=True)
    op.create_index(op.f('ix_brand_groups_fingerprint'), 'brand_groups', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_cbp_data_naics_code'), 'cbp_data', ['naics_code'], unique=False)
    op.create_index(op.f('ix_cbp_data_region'), 'cbp_data', ['region'], unique=False)
    op.create_index(op.f('ix_cbp_data_zip_code'), 'cbp_data', ['zip_code'], unique=False)
    op.create_unique_constraint('uq_cbp_record', 'cbp_data', ['zip_code', 'naics_code', 'year'])
    op.create_index(op.f('ix_chain_locations_brand_key'), 'chain_locations', ['brand_key'], unique=False)
    op.create_index(op.f('ix_chain_locations_chain'), 'chain_locations', ['chain'], unique=False)
    op.create_index(op.f('ix_chain_locations_h3_r8'), 'chain_locations', ['h3_r8'], unique=False)
    op.create_index(op.f('ix_chain_locations_h3_r9'), 'chain_locations', ['h3_r9'], unique=False)
    op.create_index(op.f('ix_chain_locations_region'), 'chain_locations', ['region'], unique=False)
    op.create_index('ix_job_posting_detail_gin', 'job_postings', ['detail_json'], unique=False, postgresql_using='gin')
    op.create_index('ix_job_postings_active_region', 'job_postings', ['is_active', 'region'], unique=False)
    op.create_index('ix_job_postings_employer_active', 'job_postings', ['local_employer_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_job_postings_expires_at'), 'job_postings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_job_postings_fingerprint'), 'job_postings', ['fingerprint'], unique=False)
    op.create_index('ix_job_postings_fp_active', 'job_postings', ['fingerprint', 'is_active'], unique=False)
    op.create_index(op.f('ix_job_postings_h3_r7'), 'job_postings', ['h3_r7'], unique=False)
    op.create_index(op.f('ix_job_postings_h3_r8'), 'job_postings', ['h3_r8'], unique=False)
    op.create_index('ix_job_postings_h3r7_active', 'job_postings', ['h3_r7', 'is_active'], unique=False)
    op.create_index('ix_job_postings_h3r8_active', 'job_postings', ['h3_r8', 'is_active'], unique=False)
    op.create_index(op.f('ix_job_postings_industry'), 'job_postings', ['industry'], unique=False)
    op.create_index(op.f('ix_job_postings_is_active'), 'job_postings', ['is_active'], unique=False)
    op.create_index(op.f('ix_job_postings_local_employer_id'), 'job_postings', ['local_employer_id'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_date'), 'job_postings', ['posted_date'], unique=False)
    op.create_index(op.f('ix_job_postings_region'), 'job_postings', ['region'], unique=False)
    op.create_index('ix_job_postings_region_industry_active', 'job_postings', ['region', 'industry', 'is_active'], unique=False)
    op.create_index(op.f('ix_job_postings_source'), 'job_postings', ['source'], unique=False)
    op.create_unique_constraint('uq_job_posting_source_external', 'job_postings', ['source', 'external_id'])
    op.create_foreign_key(None, 'job_postings', 'local_employers', ['local_employer_id'], ['id'])
    op.create_unique_constraint('uq_jolts_record', 'jolts_data', ['series_id', 'year', 'month'])
    op.create_index(op.f('ix_labor_market_baseline_region'), 'labor_market_baseline', ['region'], unique=False)
    op.create_unique_constraint('uq_labor_baseline', 'labor_market_baseline', ['region', 'naics_code', 'period_label'])
    op.create_index(op.f('ix_laus_data_fips_code'), 'laus_data', ['fips_code'], unique=False)
    op.create_index(op.f('ix_laus_data_region'), 'laus_data', ['region'], unique=False)
    op.create_unique_constraint('uq_laus_record', 'laus_data', ['fips_code', 'year', 'month'])
    op.create_index(op.f('ix_local_employers_brand_group_id'), 'local_employers', ['brand_group_id'], unique=False)
    op.create_index(op.f('ix_local_employers_fingerprint'), 'local_employers', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_local_employers_h3_r6'), 'local_employers', ['h3_r6'], unique=False)
    op.create_index(op.f('ix_local_employers_h3_r7'), 'local_employers', ['h3_r7'], unique=False)
    op.create_index(op.f('ix_local_employers_h3_r8'), 'local_employers', ['h3_r8'], unique=False)
    op.create_index(op.f('ix_local_employers_h3_r9'), 'local_employers', ['h3_r9'], unique=False)
    op.create_index(op.f('ix_local_employers_overture_id'), 'local_employers', ['overture_id'], unique=False)
    op.create_unique_constraint('uq_local_employer_fp_region', 'local_employers', ['fingerprint', 'region'])
    op.create_foreign_key(None, 'local_employers', 'brand_groups', ['brand_group_id'], ['id'])
    op.create_index('idx_source_timestamp', 'meta_api_calls', ['api_source', 'request_timestamp'], unique=False)
    op.create_index('idx_success', 'meta_api_calls', ['success'], unique=False)
    op.create_index(op.f('ix_meta_api_calls_api_source'), 'meta_api_calls', ['api_source'], unique=False)
    op.create_index(op.f('ix_meta_api_calls_request_timestamp'), 'meta_api_calls', ['request_timestamp'], unique=False)
    op.create_index('idx_table_column', 'meta_column_catalog', ['table_name', 'column_name'], unique=False)
    op.create_index(op.f('ix_meta_column_catalog_table_name'), 'meta_column_catalog', ['table_name'], unique=False)
    op.create_index('idx_source_target', 'meta_data_lineage', ['source_table', 'target_table'], unique=False)
    op.create_index(op.f('ix_meta_data_lineage_source_table'), 'meta_data_lineage', ['source_table'], unique=False)
    op.create_index(op.f('ix_meta_data_lineage_target_table'), 'meta_data_lineage', ['target_table'], unique=False)
    op.create_index('idx_job_timestamp', 'meta_job_runs', ['job_id', 'run_timestamp'], unique=False)
    op.create_index('idx_status', 'meta_job_runs', ['status'], unique=False)
    op.create_index(op.f('ix_meta_job_runs_job_id'), 'meta_job_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_meta_job_runs_run_timestamp'), 'meta_job_runs', ['run_timestamp'], unique=False)
    op.create_index('idx_entity', 'meta_table_catalog', ['entity'], unique=False)
    op.create_index('idx_layer_source', 'meta_table_catalog', ['layer', 'source'], unique=False)
    op.create_index(op.f('ix_meta_table_catalog_table_name'), 'meta_table_catalog', ['table_name'], unique=True)
    op.create_index(op.f('ix_mob_occupation_census_code'), 'mob_occupation', ['census_code'], unique=False)
    op.create_index(op.f('ix_mob_occupation_internal_industry'), 'mob_occupation', ['internal_industry'], unique=False)
    op.create_index(op.f('ix_mob_transition_dest_soc'), 'mob_transition', ['dest_soc'], unique=False)
    op.create_index('ix_mob_transition_origin_direction', 'mob_transition', ['origin_soc', 'wage_direction'], unique=False)
    op.create_index(op.f('ix_mob_transition_origin_soc'), 'mob_transition', ['origin_soc'], unique=False)
    op.create_unique_constraint('uq_mob_transition', 'mob_transition', ['origin_soc', 'dest_soc'])
    op.create_index(op.f('ix_oews_data_area_code'), 'oews_data', ['area_code'], unique=False)
    op.create_index(op.f('ix_oews_data_occ_code'), 'oews_data', ['occ_code'], unique=False)
    op.create_index(op.f('ix_oews_data_region'), 'oews_data', ['region'], unique=False)
    op.create_unique_constraint('uq_oews_record', 'oews_data', ['area_code', 'occ_code', 'year'])
    op.create_index(op.f('ix_qcew_data_fips_code'), 'qcew_data', ['fips_code'], unique=False)
    op.create_index(op.f('ix_qcew_data_naics_code'), 'qcew_data', ['naics_code'], unique=False)
    op.create_index(op.f('ix_qcew_data_region'), 'qcew_data', ['region'], unique=False)
    op.create_unique_constraint('uq_qcew_record', 'qcew_data', ['fips_code', 'naics_code', 'year', 'quarter', 'ownership_code'])
    op.create_index(op.f('ix_rate_budgets_source_key'), 'rate_budgets', ['source_key'], unique=False)
    op.create_unique_constraint('uq_rate_budget_source_date', 'rate_budgets', ['source_key', 'date'])
    op.create_index(op.f('ix_ref_brands_brand_key'), 'ref_brands', ['brand_key'], unique=True)
    op.create_index(op.f('ix_ref_brands_internal_industry'), 'ref_brands', ['internal_industry'], unique=False)
    op.create_index(op.f('ix_ref_category_map_internal_industry'), 'ref_category_map', ['internal_industry'], unique=False)
    op.create_index(op.f('ix_ref_category_map_source_system'), 'ref_category_map', ['source_system'], unique=False)
    op.create_unique_constraint('uq_source_mapping', 'ref_category_map', ['source_system', 'source_value'])
    op.create_index(op.f('ix_ref_industry_internal_key'), 'ref_industry', ['internal_key'], unique=False)
    op.create_index(op.f('ix_ref_industry_naics_code'), 'ref_industry', ['naics_code'], unique=True)
    op.create_index(op.f('ix_ref_occupation_aliases_alias'), 'ref_occupation_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_ref_occupation_aliases_soc_code'), 'ref_occupation_aliases', ['soc_code'], unique=False)
    op.create_index('ix_roa_alias_soc', 'ref_occupation_aliases', ['alias', 'soc_code'], unique=False)
    op.create_index(op.f('ix_ref_regions_region_key'), 'ref_regions', ['region_key'], unique=True)
    op.create_index(op.f('ix_ref_soc_major_groups_soc2d_code'), 'ref_soc_major_groups', ['soc2d_code'], unique=True)
    op.create_index(op.f('ix_ref_texaswages_msa_name'), 'ref_texaswages', ['msa_name'], unique=False)
    op.create_index(op.f('ix_ref_texaswages_soc_code'), 'ref_texaswages', ['soc_code'], unique=False)
    op.create_index('ix_texaswages_soc_msa', 'ref_texaswages', ['soc_code', 'msa_name'], unique=False)
    op.create_unique_constraint('uq_texaswages', 'ref_texaswages', ['soc_code', 'msa_name', 'wage_tier', 'vintage_year'])
    op.create_index(op.f('ix_revelio_employment_month'), 'revelio_employment', ['month'], unique=False)
    op.create_index(op.f('ix_revelio_employment_state'), 'revelio_employment', ['state'], unique=False)
    op.create_unique_constraint('uq_revelio_employment', 'revelio_employment', ['month', 'state', 'naics2d_code', 'soc2d_code'])
    op.create_index(op.f('ix_revelio_hiring_month'), 'revelio_hiring', ['month'], unique=False)
    op.create_index(op.f('ix_revelio_hiring_state'), 'revelio_hiring', ['state'], unique=False)
    op.create_unique_constraint('uq_revelio_hiring', 'revelio_hiring', ['month', 'state', 'naics2d_code', 'soc2d_code'])
    op.create_index(op.f('ix_revelio_layoffs_month'), 'revelio_layoffs', ['month'], unique=False)
    op.create_index(op.f('ix_revelio_layoffs_state'), 'revelio_layoffs', ['state'], unique=False)
    op.create_unique_constraint('uq_revelio_layoffs', 'revelio_layoffs', ['month', 'state', 'naics2d_code', 'layoff_type'])
    op.create_index(op.f('ix_revelio_postings_month'), 'revelio_postings', ['month'], unique=False)
    op.create_index(op.f('ix_revelio_postings_state'), 'revelio_postings', ['state'], unique=False)
    op.create_unique_constraint('uq_revelio_postings', 'revelio_postings', ['month', 'state', 'naics2d_code', 'soc2d_code'])
    op.create_index(op.f('ix_revelio_salaries_month'), 'revelio_salaries', ['month'], unique=False)
    op.create_index(op.f('ix_revelio_salaries_state'), 'revelio_salaries', ['state'], unique=False)
    op.create_unique_constraint('uq_revelio_salaries', 'revelio_salaries', ['month', 'state', 'naics2d_code', 'soc2d_code'])
    op.create_index(op.f('ix_signals_source'), 'signals', ['source'], unique=False)
    op.create_index(op.f('ix_signals_store_num'), 'signals', ['store_num'], unique=False)
    op.create_index('ix_signals_store_source', 'signals', ['store_num', 'source'], unique=False)
    op.create_index(op.f('ix_snapshots_region'), 'snapshots', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_region'), table_name='snapshots')
    op.drop_index('ix_signals_store_source', table_name='signals')
    op.drop_index(op.f('ix_signals_store_num'), table_name='signals')
    op.drop_index(op.f('ix_signals_source'), table_name='signals')
    op.drop_constraint('uq_revelio_salaries', 'revelio_salaries', type_='unique')
    op.drop_index(op.f('ix_revelio_salaries_state'), table_name='revelio_salaries')
    op.drop_index(op.f('ix_revelio_salaries_month'), table_name='revelio_salaries')
    op.drop_constraint('uq_revelio_postings', 'revelio_postings', type_='unique')
    op.drop_index(op.f('ix_revelio_postings_state'), table_name='revelio_postings')
    op.drop_index(op.f('ix_revelio_postings_month'), table_name='revelio_postings')
    op.drop_constraint('uq_revelio_layoffs', 'revelio_layoffs', type_='unique')
    op.drop_index(op.f('ix_revelio_layoffs_state'), table_name='revelio_layoffs')
    op.drop_index(op.f('ix_revelio_layoffs_month'), table_name='revelio_layoffs')
    op.drop_constraint('uq_revelio_hiring', 'revelio_hiring', type_='unique')
    op.drop_index(op.f('ix_revelio_hiring_state'), table_name='revelio_hiring')
    op.drop_index(op.f('ix_revelio_hiring_month'), table_name='revelio_hiring')
    op.drop_constraint('uq_revelio_employment', 'revelio_employment', type_='unique')
    op.drop_index(op.f('ix_revelio_employment_state'), table_name='revelio_employment')
    op.drop_index(op.f('ix_revelio_employment_month'), table_name='revelio_employment')
    op.drop_constraint('uq_texaswages', 'ref_texaswages', type_='unique')
    op.drop_index('ix_texaswages_soc_msa', table_name='ref_texaswages')
    op.drop_index(op.f('ix_ref_texaswages_soc_code'), table_name='ref_texaswages')
    op.drop_index(op.f('ix_ref_texaswages_msa_name'), table_name='ref_texaswages')
    op.drop_index(op.f('ix_ref_soc_major_groups_soc2d_code'), table_name='ref_soc_major_groups')
    op.drop_index(op.f('ix_ref_regions_region_key'), table_name='ref_regions')
    op.drop_index('ix_roa_alias_soc', table_name='ref_occupation_aliases')
    op.drop_index(op.f('ix_ref_occupation_aliases_soc_code'), table_name='ref_occupation_aliases')
    op.drop_index(op.f('ix_ref_occupation_aliases_alias'), table_name='ref_occupation_aliases')
    op.drop_index(op.f('ix_ref_industry_naics_code'), table_name='ref_industry')
    op.drop_index(op.f('ix_ref_industry_internal_key'), table_name='ref_industry')
    op.drop_constraint('uq_source_mapping', 'ref_category_map', type_='unique')
    op.drop_index(op.f('ix_ref_category_map_source_system'), table_name='ref_category_map')
    op.drop_index(op.f('ix_ref_category_map_internal_industry'), table_name='ref_category_map')
    op.drop_index(op.f('ix_ref_brands_internal_industry'), table_name='ref_brands')
    op.drop_index(op.f('ix_ref_brands_brand_key'), table_name='ref_brands')
    op.drop_constraint('uq_rate_budget_source_date', 'rate_budgets', type_='unique')
    op.drop_index(op.f('ix_rate_budgets_source_key'), table_name='rate_budgets')
    op.drop_constraint('uq_qcew_record', 'qcew_data', type_='unique')
    op.drop_index(op.f('ix_qcew_data_region'), table_name='qcew_data')
    op.drop_index(op.f('ix_qcew_data_naics_code'), table_name='qcew_data')
    op.drop_index(op.f('ix_qcew_data_fips_code'), table_name='qcew_data')
    op.drop_constraint('uq_oews_record', 'oews_data', type_='unique')
    op.drop_index(op.f('ix_oews_data_region'), table_name='oews_data')
    op.drop_index(op.f('ix_oews_data_occ_code'), table_name='oews_data')
    op.drop_index(op.f('ix_oews_data_area_code'), table_name='oews_data')
    op.drop_constraint('uq_mob_transition', 'mob_transition', type_='unique')
    op.drop_index(op.f('ix_mob_transition_origin_soc'), table_name='mob_transition')
    op.drop_index('ix_mob_transition_origin_direction', table_name='mob_transition')
    op.drop_index(op.f('ix_mob_transition_dest_soc'), table_name='mob_transition')
    op.drop_index(op.f('ix_mob_occupation_internal_industry'), table_name='mob_occupation')
    op.drop_index(op.f('ix_mob_occupation_census_code'), table_name='mob_occupation')
    op.drop_index(op.f('ix_meta_table_catalog_table_name'), table_name='meta_table_catalog')
    op.drop_index('idx_layer_source', table_name='meta_table_catalog')
    op.drop_index('idx_entity', table_name='meta_table_catalog')
    op.drop_index(op.f('ix_meta_job_runs_run_timestamp'), table_name='meta_job_runs')
    op.drop_index(op.f('ix_meta_job_runs_job_id'), table_name='meta_job_runs')
    op.drop_index('idx_status', table_name='meta_job_runs')
    op.drop_index('idx_job_timestamp', table_name='meta_job_runs')
    op.drop_index(op.f('ix_meta_data_lineage_target_table'), table_name='meta_data_lineage')
    op.drop_index(op.f('ix_meta_data_lineage_source_table'), table_name='meta_data_lineage')
    op.drop_index('idx_source_target', table_name='meta_data_lineage')
    op.drop_index(op.f('ix_meta_column_catalog_table_name'), table_name='meta_column_catalog')
    op.drop_index('idx_table_column', table_name='meta_column_catalog')
    op.drop_index(op.f('ix_meta_api_calls_request_timestamp'), table_name='meta_api_calls')
    op.drop_index(op.f('ix_meta_api_calls_api_source'), table_name='meta_api_calls')
    op.drop_index('idx_success', table_name='meta_api_calls')
    op.drop_index('idx_source_timestamp', table_name='meta_api_calls')
    op.drop_constraint(None, 'local_employers', type_='foreignkey')
    op.drop_constraint('uq_local_employer_fp_region', 'local_employers', type_='unique')
    op.drop_index(op.f('ix_local_employers_overture_id'), table_name='local_employers')
    op.drop_index(op.f('ix_local_employers_h3_r9'), table_name='local_employers')
    op.drop_index(op.f('ix_local_employers_h3_r8'), table_name='local_employers')
    op.drop_index(op.f('ix_local_employers_h3_r7'), table_name='local_employers')
    op.drop_index(op.f('ix_local_employers_h3_r6'), table_name='local_employers')
    op.drop_index(op.f('ix_local_employers_fingerprint'), table_name='local_employers')
    op.drop_index(op.f('ix_local_employers_brand_group_id'), table_name='local_employers')
    op.drop_constraint('uq_laus_record', 'laus_data', type_='unique')
    op.drop_index(op.f('ix_laus_data_region'), table_name='laus_data')
    op.drop_index(op.f('ix_laus_data_fips_code'), table_name='laus_data')
    op.drop_constraint('uq_labor_baseline', 'labor_market_baseline', type_='unique')
    op.drop_index(op.f('ix_labor_market_baseline_region'), table_name='labor_market_baseline')
    op.drop_constraint('uq_jolts_record', 'jolts_data', type_='unique')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint('uq_job_posting_source_external', 'job_postings', type_='unique')
    op.drop_index(op.f('ix_job_postings_source'), table_name='job_postings')
    op.drop_index('ix_job_postings_region_industry_active', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_region'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_date'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_local_employer_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_is_active'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_industry'), table_name='job_postings')
    op.drop_index('ix_job_postings_h3r8_active', table_name='job_postings')
    op.drop_index('ix_job_postings_h3r7_active', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_h3_r8'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_h3_r7'), table_name='job_postings')
    op.drop_index('ix_job_postings_fp_active', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_fingerprint'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_expires_at'), table_name='job_postings')
    op.drop_index('ix_job_postings_employer_active', table_name='job_postings')
    op.drop_index('ix_job_postings_active_region', table_name='job_postings')
    op.drop_index('ix_job_posting_detail_gin', table_name='job_postings', postgresql_using='gin')
    op.drop_index(op.f('ix_chain_locations_region'), table_name='chain_locations')
    op.drop_index(op.f('ix_chain_locations_h3_r9'), table_name='chain_locations')
    op.drop_index(op.f('ix_chain_locations_h3_r8'), table_name='chain_locations')
    op.drop_index(op.f('ix_chain_locations_chain'), table_name='chain_locations')
    op.drop_index(op.f('ix_chain_locations_brand_key'), table_name='chain_locations')
    op.drop_constraint('uq_cbp_record', 'cbp_data', type_='unique')
    op.drop_index(op.f('ix_cbp_data_zip_code'), table_name='cbp_data')
    op.drop_index(op.f('ix_cbp_data_region'), table_name='cbp_data')
    op.drop_index(op.f('ix_cbp_data_naics_code'), table_name='cbp_data')
    op.drop_index(op.f('ix_brand_groups_fingerprint'), table_name='brand_groups')
    op.drop_index(op.f('ix_api_sources_source_key'), table_name='api_sources')
    op.drop_index(op.f('ix_api_request_log_source_key'), table_name='api_request_log')
    op.drop_index(op.f('ix_api_request_log_requested_at'), table_name='api_request_log')
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index('ix_events_start_active', table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_region'), table_name='events')
    op.drop_index(op.f('ix_events_is_active'), table_name='events')
    op.drop_index('ix_events_h3r8_active', table_name='events')
    op.drop_index('ix_events_h3r7_active', table_name='events')
    op.drop_index(op.f('ix_events_h3_r8'), table_name='events')
    op.drop_index(op.f('ix_events_h3_r7'), table_name='events')
    op.drop_index(op.f('ix_events_expires_at'), table_name='events')
    op.drop_index('ix_events_category_active_region', table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_index('ix_events_active_region', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_venues_region'), table_name='venues')
    op.drop_index(op.f('ix_venues_h3_r9'), table_name='venues')
    op.drop_index(op.f('ix_venues_h3_r8'), table_name='venues')
    op.drop_index(op.f('ix_venues_h3_r7'), table_name='venues')
    op.drop_index(op.f('ix_venues_fingerprint'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
