"""
openclaw/wishlist.py — Daily wishlist generated by the agent.

Once per day (or on demand) the agent reflects on what data sources,
tools, or search terms it WISHES it had.  These get logged to disk
as structured requests that a human operator can review and approve.

The wishlist has three categories:
  1. NEW_SOURCE     — "I wish I had access to Indeed API directly"
  2. NEW_TERM       — "I wish 'matcha bar' was an approved POI search term for coffee_cafe"
  3. NEW_INDUSTRY   — "I wish 'pet care' was in the industry registry"
  4. NEW_BRAND      — "I wish 'Philz Coffee' was a tracked mega-corp"
  5. TOOL_REQUEST   — "I wish I could geocode addresses to lat/lng"

Operators can approve items, which auto-patches the running config
or flags items for the next code deploy.
"""

from __future__ import annotations

import json
import logging
import threading
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
WISHLIST_DIR = _PROJECT_ROOT / "data" / "openclaw_wishlists"


class WishCategory(str, Enum):
    NEW_SOURCE = "new_source"
    NEW_TERM = "new_term"
    NEW_INDUSTRY = "new_industry"
    NEW_BRAND = "new_brand"
    TOOL_REQUEST = "tool_request"


class WishStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    IMPLEMENTED = "implemented"


@dataclass
class WishItem:
    """A single wish from the agent."""
    wish_id: str
    category: str             # WishCategory value
    title: str                # Short summary
    description: str          # Agent's reasoning
    suggested_value: str      # e.g. the term, source name, industry key
    context: dict = field(default_factory=dict)  # supporting data
    status: str = "pending"   # WishStatus value
    created_at: str = ""
    reviewed_at: Optional[str] = None
    reviewer_note: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "wish_id": self.wish_id,
            "category": self.category,
            "title": self.title,
            "description": self.description,
            "suggested_value": self.suggested_value,
            "context": self.context,
            "status": self.status,
            "created_at": self.created_at,
            "reviewed_at": self.reviewed_at,
            "reviewer_note": self.reviewer_note,
        }


@dataclass
class DailyWishlist:
    """All wishes for a single day."""
    date: str
    items: list[WishItem] = field(default_factory=list)
    generated_by_model: str = ""
    session_summary: str = ""

    def to_dict(self) -> dict:
        return {
            "date": self.date,
            "generated_by_model": self.generated_by_model,
            "session_summary": self.session_summary,
            "count": len(self.items),
            "items": [i.to_dict() for i in self.items],
        }


class WishlistManager:
    """Manages daily wishlists from the agent.

    Thread-safe.  Stores one wishlist file per day in
    data/openclaw_wishlists/wishlist_YYYY-MM-DD.json
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._today: str = datetime.utcnow().strftime("%Y-%m-%d")
        self._current: DailyWishlist = DailyWishlist(date=self._today)
        self._counter: int = 0
        WISHLIST_DIR.mkdir(parents=True, exist_ok=True)

    def _rotate_if_needed(self) -> None:
        today = datetime.utcnow().strftime("%Y-%m-%d")
        if today != self._today:
            if self._current.items:
                self._save(self._current)
            self._today = today
            self._current = DailyWishlist(date=today)
            self._counter = 0

    def add_wish(
        self,
        category: str,
        title: str,
        description: str,
        suggested_value: str,
        context: Optional[dict] = None,
        model: str = "",
    ) -> WishItem:
        """Add a wish from the agent."""
        with self._lock:
            self._rotate_if_needed()
            self._counter += 1
            wish = WishItem(
                wish_id=f"wish-{self._today}-{self._counter:03d}",
                category=category,
                title=title,
                description=description,
                suggested_value=suggested_value,
                context=context or {},
                created_at=datetime.utcnow().isoformat(),
            )
            self._current.items.append(wish)
            self._current.generated_by_model = model or self._current.generated_by_model
            logger.info("[Wishlist] Added: %s — %s", wish.wish_id, title)
            return wish

    def get_today(self) -> DailyWishlist:
        """Return today's wishlist."""
        with self._lock:
            self._rotate_if_needed()
            return self._current

    def get_wishlist(self, date: str) -> Optional[DailyWishlist]:
        """Load a wishlist for a specific date."""
        if date == self._today:
            return self.get_today()
        return self._load(date)

    def get_pending(self) -> list[dict]:
        """Return all pending wish items from today."""
        with self._lock:
            self._rotate_if_needed()
            return [
                w.to_dict() for w in self._current.items
                if w.status == WishStatus.PENDING.value
            ]

    def review_wish(self, wish_id: str, approved: bool, note: str = "") -> Optional[dict]:
        """Approve or reject a wish item."""
        with self._lock:
            for w in self._current.items:
                if w.wish_id == wish_id:
                    w.status = WishStatus.APPROVED.value if approved else WishStatus.REJECTED.value
                    w.reviewed_at = datetime.utcnow().isoformat()
                    w.reviewer_note = note
                    logger.info("[Wishlist] Reviewed %s: %s", wish_id, w.status)
                    return w.to_dict()
        return None

    def set_session_summary(self, summary: str) -> None:
        """Set the session summary for today's wishlist."""
        with self._lock:
            self._current.session_summary = summary

    def save_now(self) -> None:
        """Force-save today's wishlist to disk."""
        with self._lock:
            if self._current.items:
                self._save(self._current)

    def _save(self, wl: DailyWishlist) -> None:
        path = WISHLIST_DIR / f"wishlist_{wl.date}.json"
        try:
            path.write_text(json.dumps(wl.to_dict(), indent=2), encoding="utf-8")
            logger.info("[Wishlist] Saved %d items to %s", len(wl.items), path)
        except Exception as e:
            logger.error("[Wishlist] Failed to save: %s", e)

    def _load(self, date: str) -> Optional[DailyWishlist]:
        path = WISHLIST_DIR / f"wishlist_{date}.json"
        if not path.exists():
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            wl = DailyWishlist(
                date=data["date"],
                generated_by_model=data.get("generated_by_model", ""),
                session_summary=data.get("session_summary", ""),
            )
            for item_data in data.get("items", []):
                wl.items.append(WishItem(**item_data))
            return wl
        except Exception as e:
            logger.error("[Wishlist] Failed to load %s: %s", path, e)
            return None


# Module-level singleton
wishlist_manager = WishlistManager()
